package(default_visibility = ["//visibility:public"])

py_library(
    name = "distbase",
    srcs = [
        "distbase.py",
    ],
    deps = [
        "//model/cs:csh",
        "//model/cs:random",
        "//model/rl/agent:vec_agent",
        "//model/utils:vectorization",
    ],
)

py_library(
    name = "syncsgd",
    srcs = [
        "syncsgd.py",
    ],
    deps = [
        "//model/cs:csh",
        "//model/cs:random",
        "//model/rl/agent:vec_agent",
        "//model/utils:vectorization",
    ],
)
