package(default_visibility = ["//visibility:public"])

py_library(
    name = "cs",
    srcs = [
        "cs.py",
    ],
)

py_library(
    name = "csh",
    srcs = [
        "csh.py",
    ],
    deps = [
        "//model/cs:cs",
    ],
)

py_library(
    name = "random",
    srcs = [
        "random.py",
    ],
    deps = [
        "//model/cs:cs",
    ],
)

py_library(
    name = "powd",
    srcs = [
        "powd.py",
    ],
    deps = [
        "//model/cs:cs",
    ],
)

py_library(
    name = "gradnorm",
    srcs = [
        "gradnorm.py",
    ],
    deps = [
        "//model/cs:cs",
    ],
)
